name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  VITE_ENV: "ci"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      # Bump package versions based on changesets and commit changes to the main branch
      - name: Bump package versions
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        run: |
          git config user.name toolsvenus
          git config user.email tools@venus.io
          git fetch origin
          git rebase --strategy-option=theirs origin/main
          npx changeset version
          git add -A
          git status
          git commit --verbose -a -m "chore: bump package versions" || exit 0
          git push

      - name: Build
        env:
          VITE_NETWORK: "mainnet"
          VITE_ENV: "production"
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
          VITE_POSTHOG_API_KEY: ${{ secrets.VITE_POSTHOG_API_KEY }}
          VITE_POSTHOG_HOST_URL: ${{ secrets.VITE_POSTHOG_HOST_URL }}
          VITE_ZYFI_API_KEY: ${{ secrets.VITE_ZYFI_API_KEY }}
          VITE_NODE_REAL_API_KEY: ${{ secrets.VITE_NODE_REAL_API_KEY }}
          VITE_THE_GRAPH_API_KEY: ${{ secrets.VITE_THE_GRAPH_API_KEY }}
        run: |
          # We only build the dApp because the landing page is deployed with Vercel
          yarn build --filter=@venusprotocol/evm
          ls

      # - name: Upload to IPFS and pin
      #   env:


      # - name: Update DNS record